server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, /cancellations/** 
        - id: customercenter
          uri: http://localhost:8083
          predicates:
            - Path=/mypages/**           
        - id: product
          uri: http://localhost:8084
          predicates:
            - Path=/products/**   
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
      - id: order
          uri: http://localhost:8080
          predicates:
            - Path=/orders/** 
      - id: delivery
          uri: http://localhost:8080
          predicates:
            - Path=/deliveries/**, /cancellations/** 
      - id: customercenter
          uri: http://localhost:8080
          predicates:
            - Path=/mypages/**           
      - id: product
          uri: http://localhost:8080
          predicates:
            - Path=/products/**   
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
