apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order
  namespace: deliveryhero
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5
